tell people to give up trying to downgrade an X
Arna13/sunst0rm-guide pull request #29
Opened 2022-10-30 04:27 UTC by DarwinUang

https://canary.discord.com/channels/948247189837189191/948247189837189194/1032494943404572752

2022-10-30 12:12 UTC, Arna13 requested changes

2022-10-30 12:12 UTC, Arna13 commented on docs/wherecanigo.md
> +- [Touch might be broken on downgrades](https://discord.com/channels/948247189837189191/948247189837189194/1032494943404572752)
I think the link is not needed
```suggestion
- Touch might be broken on downgrades
```

Otherwise this PR is fine, I would just change that since the link doesnt provide an actual explanation and needs the reader to have Discord and join miniexploit's server.

2022-10-30 21:44 UTC, Beast9265 commented
the only way i think touch screen works on iphone x if they had there display replaced with a lcd i think its because of the oled the touch just doesn't work for some reason

2022-10-31 12:15 UTC, Arna13 approved these changes

2022-10-31 12:15 UTC, merged